#pragma once

enum TimeEditField {
	TIME_EDIT_YEAR,
	TIME_EDIT_MONTH,
	TIME_EDIT_DAY,
	TIME_EDIT_HOUR,
	TIME_EDIT_MINUTE,
	TIME_EDIT_SECOND,
	TIME_EDIT_CONFIRM
};

enum ScheduleEditField {
	SCHEDULE_EDIT_DAY,
	SCHEDULE_EDIT_START,
	SCHEDULE_EDIT_STOP,
	SCHEDULE_EDIT_ACCELERATION
};